### ISSUE TITLE
Bitrate is set statically

### ISSUE THREAD

**Issue by Pyrogeen** [RandomNinjaAtk/lidarr-automated-downloader#13]
In the script on line 63 the bitrate is set to `"320"` instead of `"${ConversionBitrate}"`.

https://github.com/RandomNinjaAtk/lidarr-automated-downloader/blob/a5fe99792ee0be8924847ffd71413d3583576a41/lidarr-automated-downloader.bash#L63

**Comment by RandomNinjaAtk** [comment]
I'm not sure what your trying to say, the two are not related at all....

**Comment by Pyrogeen** [comment]
When I set `ConversionBitrate` to 128 it doesnt do anything, it keeps downloading 320kbps files, I have to change the `dlquality` in the script to make it download at the right bitrate.

**Comment by RandomNinjaAtk** [comment]
Right now the conversion bitrate only applies to non MP3 and FLAC formats. so if you want 128, you currently need to select OPUS or AAC. Since MP3 is natively provided by the DL client, it is not converted to the desired bitrate.

Edit:
The only way I could easily see making it work, would be to only download lossless and convert to all formats. It would require extra processing, but keeps things simple...

**Comment by Pyrogeen** [comment]
I do mean the MP3 format, the DL client provides 128kbps and 320kbps MP3, but I cant choose the 128kbps MP3, it just keeps downloading the 320kbps one.

EDIT: I think I got the term `ConversionBitrate` wrong, so there just isn't an option to choose 128kbps MP3 right now?

**Comment by RandomNinjaAtk** [comment]
There's really only an option to choose main format, ie: flac, opus, mp3 and etc. The conversion bitrate is used when converting to specified formats (opus, aac). Because MP3 is native, its not converted and uses the default dl quality of 320. 

The original idea was to keep it simple, just choose a format and that's it...'

Edit:

If your target is that low of bitrate, I'd recommend to use OPUS format to get the maximum quality at that bitrate.

**Comment by Pyrogeen** [comment]
Okay, thanks for the explanation.

**Comment by RandomNinjaAtk** [comment]
@Pyrogeen I modified the script, so you can use any bitrate you want technically now. Everything is grabbed in lossless and then converted to the desired format at the matching bitrate. I understand this is probably not ideally what you want but it's the easiest way to satisfy every possible situation.

You could alternatively just modify the script to only download the format you want.

**Comment by RandomNinjaAtk** [comment]
@Pyrogeen Actually on second thought, I just thought of a seamless way I could get the functionality you wanted put into the script. No conversion necessary. I'll let you know in a update here once I implement the change. #soon

**Comment by RandomNinjaAtk** [comment]
@Pyrogeen 
Should be fixed with this https://github.com/RandomNinjaAtk/lidarr-automated-downloader/commit/a0ce954b39f2fe549746af5795f13a6ea8baa560

I have not tested it, so give it a try and let me know. You need the latest version of the script, because I did do one bugfix commit after that change for this feature.

It basically only downloads if you select MP3, and the Conversion Bitrate Matches a native format, otherwise it will only download lossless and convert....

For low bitrates, I'd recommend you use opus instead to maximize quality and save on file size.

**Comment by RandomNinjaAtk** [comment]
I assume this is resolved...

**Comment by Pyrogeen** [comment]
Sorry I was a bit busy with my finals.
Yes this is working perfectly, thank you.
