### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Adrian-Rasmussen** [RandomNinjaAtk/lidarr-automated-downloader#5]
Is it possible to add support for Windows (using WSL) similar to what was done for the previous script?
https://github.com/Migz93/lidarr-download-automation/pull/14

**Comment by RandomNinjaAtk** [comment]
Pull requests welcome, but I'd recommend just running the official docker on top of windows, because that would be far simpler...

Or use a VM with ubuntu 18.04. My main focus is for this to work in the official docker (I do all my testing on it). So, I won't be enabling that unless someone else writes a PR for it.

Edit:
It may work if you install all the software packages using WSL2. I've not tested it....
